version: '3.9'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker_files/env.dev
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    env_file:
      - ./docker_files/env.dev