version: '3.7'
services:
  web:
    build: ./tradeplatform
    volumes:
      - ./tradeplatform:/usr/src/app/
    env_file:
      - ./tradeplatform/env.dev
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:13.1-alpine
    volumes:
      - ./tradeplatform/pg_data:/var/lib/postgresql/data/
    env_file:
      - ./tradeplatform/env.dev

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build: ./tradeplatform
    volumes:
      - .:/usr/src/app/
    entrypoint: celery --workdir=tradeplatform -A core worker -l info
    env_file:
      - ./tradeplatform/env.dev
    depends_on:
      - db
      - redis
    restart: on-failure

  celery-beat:
    build: ./tradeplatform
    volumes:
      - ./tradeplatform:/usr/src/app/
    entrypoint: celery -A core beat -l info
    env_file:
      - ./tradeplatform/env.dev
    depends_on:
      - db
      - redis
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./tradeplatform/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./tradeplatform/static:/usr/src/app/static/
    ports:
      - 8000:80
    depends_on:
      - web
